name: Dev Branch CI

on:
  push:
    branches: [ dev ]

jobs:
  #  lint:
  #    name: ğŸ” Lint
  #    runs-on: ubuntu-latest
  #    steps:
  #
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Lint
  #        run: bash ./gradlew lintDebug
  #
  #      - name: Generate lint report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: lint_report.html
  #          path: app/build/reports/lint-results-debug.html

  #  unit-test:
  #    name: ğŸ§ª Unit Test
  #    needs: [ lint ]
  #    runs-on: ubuntu-latest
  #    steps:
  #
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Execute unit tests
  #        run: bash ./gradlew test
  #
  #      - name: Generate test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: unit_test_report.html
  #          path: app/build/reports/tests/testDebugUnitTest/

  #  static-code-analysis:
  #    name: ğŸ•¶ Static Code Analysis
  #    #    needs: [ unit-test, instrumentation-test ]
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Set up JDK 11
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 11
  #
  #      - name: SonarCloud scan
  #        run: bash ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: ğŸ— Build Apk
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug
        run: bash ./gradlew assembleDebug

  deploy:
    name: ğŸš€ Deploy to Firebase App Distribution
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload artifcat to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Beta Testers
          file: app/build/outputs/apk/debug/app-debug.apk